luminosity_function:
  type: "DPL"
  alpha: -2.08
  beta: -4.81
  M_star: -21.01
  phi_star: 10**(-3.74)
  Muv_range: [-25, -20]  # Minimum and maximum mag values
  reference: "Harikane+24"
  n_samples: 1000
  dMuv: 0.1

source_injection:
  beta_mean: -2
  beta_std: 0.2
  zmin: 6.5
  zmax: 7.5
  dz: 0.05
  filters: ['Y', 'J']
  image_size_arcmin: 10
  n_images: 1000
  base_image: "UVISTA_YJ_DR6.fits"

source_extraction:
  batch_size: 100
