"""
spawn_imageslis_files.py

Using the tile ID to tile index dictionary generated by plot_mosaic.py, we can now create an images.lis file with an entry for each tile.
They will be labelled Y_1, Y_2, etc.

Created: Wednesday 20th March 2024.
"""

import numpy as np
from pathlib import Path
import glob
import os

euclid_dir = Path.home() / 'euclid'

tile_dict = np.load(Path.cwd().parent.parent / 'data' / 'mosaic' / 'tile_index_map.npy', allow_pickle=True)
print(tile_dict)

filter_names = ['VIS', 'Y', 'J', 'H']

field_name = 'COSMOS'

for filter_name in filter_names:

    image_dir = euclid_dir / filter_name / 'COSMOS'

    for tile, index in tile_dict.item().items():
        print(tile, index)

        image_stub = glob.glob(str(image_dir/ f'*BGSUB*{tile}*'))
        weight_stub = glob.glob(str(image_dir/ f'*RMS*{tile}*'))

        image = image_stub[0].split('/')[-1]
        image = image[:-5] + f'_{index}.fits' # Add tile index to file name

        if len(weight_stub) == 1:
            weight = weight_stub[0].split('/')[-1]
            weight = weight[:-5] + f'_{index}.fits'
        if len(weight_stub) == 0:
            weight = 'NONE'

        print(image, weight)


        with open(Path.home() / 'euclid' / filter_name / field_name / 'images.lis', 'a') as f:
            if index == 1:
                f.write(f'#Name  Tile   Image   Weight  wht_type    zeropoint   filter  directory   mask\n')
            
            f.write(f'{filter_name}_{index} {tile}  {image} {weight} RMS 29.8 {filter_name} here none\n')
